#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 A/B/A.pm" v1.030 run by joe on Wed Apr 19 10:00:50 2023
import builtins, perllib, types

perllib.init_package("A.B.A", is_class=True)


def hello(*_args):
    return "Hello from A::B::A!"


A.B.A.hello = hello


def new(*_args):
    [class_] = perllib.list_of_n(_args, 1)
    return perllib.bless(perllib.Hash(), class_)


A.B.A.new = types.MethodType(new, A.B.A)
builtins.__PACKAGE__ = "A.B.A"

# SKIPPED: use strict;
perllib.WARNING = 1
