#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./My/BaseClass.pm" v1.026 run by JO2742 on Wed Feb 15 23:58:54 2023
# Part of test_use_parent2.pl - generated by chatGPT
import builtins, perllib, types

perllib.init_package("My.BaseClass", is_class=True)


def attribute(*_args):
    _args = list(_args)
    return (_args.pop(0) if _args else None)["attribute"]


My.BaseClass.attribute = attribute


def foo(*_args):
    return "foo"


My.BaseClass.foo = foo


def new(*_args):
    _args = list(_args)
    class_ = _args.pop(0) if _args else None
    self = perllib.bless(perllib.Hash(), class_)
    self["attribute"] = "value"
    return self


My.BaseClass.new = types.MethodType(new, My.BaseClass)
builtins.__PACKAGE__ = "My.BaseClass"
