# Part of test_use_parent2.pl - generated by chatGPT
package My::BaseClass;
sub new {
    my $class = shift;
    my $self = bless {}, $class;
    $self->{attribute} = 'value';
    return $self;
}
sub foo { 'foo' }
sub attribute { shift->{attribute} }
1;

