#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./My/Mixin.pm" v1.021 run by JO2742 on Thu Jan  5 23:38:09 2023
# Part of test_use_parent2.pl - generated by chatGPT
import builtins, perllib

perllib.init_package("My.Mixin")


def bar(*_args):
    return "bar"


My.Mixin.bar = bar

builtins.__PACKAGE__ = "My.Mixin"
