#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./My/Mixin.pm" v1.024 run by JO2742 on Sun Feb  5 10:24:25 2023
# Part of test_use_parent2.pl - generated by chatGPT
import builtins, perllib

perllib.init_package("My.Mixin")


def bar(*_args):
    return "bar"


My.Mixin.bar = bar

builtins.__PACKAGE__ = "My.Mixin"
