#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./subdir/subsubdir/utils.pm" v1.029 run by JO2742 on Sun Mar 26 10:43:44 2023
# part of issue_s211 - check a subsubdir
import builtins, perllib
from Exporter import import_

builtins.__PACKAGE__ = "subdir.subsubdir.utils"
Exporter.import_("Exporter", "import")
perllib.init_package("subdir.subsubdir.utils")


def myutil(*_args):
    return perllib.num(_args[0]) + 1


subdir.subsubdir.utils.myutil = myutil

builtins.__PACKAGE__ = "subdir.subsubdir.utils"

subdir.subsubdir.utils.import_ = import_

subdir.subsubdir.utils.EXPORT_OK_a = "myutil".split()
