#!/usr/bin/env python3
# Generated by "pythonizer -v0 subdir/debug.pl" v1.005 run by JO2742 on Sun Oct 23 00:47:22 2022
# Defines a debug variable for testing require

import perllib, builtins

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
main.Debug_v = 1
