#!/usr/bin/env python3
# Generated by "pythonizer -v0 subdir/debug.pl" v1.004 run by JO2742 on Thu Oct 20 17:27:26 2022
# Defines a debug variable for testing require

import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
main.Debug_v = 1
