#!/usr/bin/env python3
# Generated by "main.py -v0 subdir/debug.pl" v1.001 run by JO2742 on Tue Oct 11 15:58:57 2022
# Defines a debug variable for testing require

import perllib, builtins

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
main.Debug_v = 1
