#!/usr/bin/env python3
# Generated by "pythonizer -v0 subdir/debug.pl" v1.029 run by JO2742 on Sun Mar 26 10:43:57 2023
# Defines a debug variable for testing require

import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
main.Debug_v = 1
