#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 subdir/FindMe.pm" v1.022 run by JO2742 on Wed Jan 18 07:31:10 2023
import builtins, perllib

perllib.init_package("FindMe")
builtins.__PACKAGE__ = "FindMe"
# SKIPPED: require Exporter;
FindMe.ISA_a = "Exporter".split()
FindMe.EXPORT_a = "$findme".split()
FindMe.EXPORT_OK_a = "$findme".split()
FindMe.findme_v = 1
