#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 subdir/FindMe.pm" v1.020 run by JO2742 on Tue Dec 27 18:47:05 2022
import builtins, perllib

perllib.init_package("FindMe")
builtins.__PACKAGE__ = "FindMe"
# SKIPPED: require Exporter;
FindMe.ISA_a = "Exporter".split()
FindMe.EXPORT_a = "$findme".split()
FindMe.EXPORT_OK_a = "$findme".split()
FindMe.findme_v = 1
