#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./subdir/Util.pm" v1.023 run by JO2742 on Mon Jan 30 23:23:16 2023
# Part of issue_s211
import builtins, perllib

perllib.init_package("subdir.Util")


def escape(*_args):
    return _args[0]


subdir.Util.escape = escape

builtins.__PACKAGE__ = "subdir.Util"
# SKIPPED: use Exporter qw/import/;
subdir.Util.EXPORT_OK_a = "escape".split()
