#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_2_arrays.pl" v1.028 run by JO2742 on Wed Mar  1 23:02:18 2023
# part of issue_s292: die with two arrays
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
diearray = perllib.Array(["Die with", "array"])
twoarray = perllib.Array(["second", "array\n"])
perllib.die(*diearray, *twoarray)
