#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_func.pl" v1.028 run by JO2742 on Wed Mar  1 23:02:21 2023
# part of issue_s292: die as function with string
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
perllib.die("function")
