#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_str.pl" v1.030 run by joe on Wed Apr 19 09:52:29 2023
# part of issue_s292: die with string
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
perllib.die("my exception")
