#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_multiple_with_nl.pl" v1.027 run by JO2742 on Thu Feb 23 22:13:12 2023
# part of issue_s292: die with multiple items and newline
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
perllib.die("die", "with", "multiple", "items", "and", "newline\n")
