#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_multiple_with_nl.pl" v1.030 run by joe on Wed Apr 19 09:52:25 2023
# part of issue_s292: die with multiple items and newline
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
perllib.die("die", "with", "multiple", "items", "and", "newline\n")
