#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_with_input_bare.pl" v1.028 run by JO2742 on Wed Mar  1 23:02:31 2023
# part of issue_s292: die with $. in the message, bare FH
import builtins, perllib, sys

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
main.IN = perllib.open_(f"{sys.argv[0]}", "r", checked=False)
line = perllib.readline_full(main.IN, "IN")
perllib.die("die with bare fh input")
