#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_2_arrays.pl" v1.030 run by joe on Wed Apr 19 09:52:22 2023
# part of issue_s292: die with two arrays
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
diearray = perllib.Array(["Die with", "array"])
twoarray = perllib.Array(["second", "array\n"])
perllib.die(*diearray, *twoarray)
