#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_no_args_with_propagate.pl" v1.027 run by JO2742 on Thu Feb 23 22:13:19 2023
# part of issue_s292: die w/o args with eval_error
# If LIST was empty or made an empty string, and $@ contains an object reference that has a PROPAGATE method, that method will be called with additional file and line number parameters. The return value replaces the value in $@; i.e., as if $@ = eval { $@->PROPAGATE(__FILE__, __LINE__) }; were called.
import builtins, perllib, types

_bn = lambda s: "" if s is None else s
perllib.init_package("main")
perllib.init_package("Class", is_class=True)


def PROPAGATE(*_args):
    _args = list(_args)
    self = _args.pop(0) if _args else None
    [file, lno] = perllib.list_of_n(_args, 2)
    return f"PROPAGATE({_bn(file)}, {_bn(lno)})"


Class.PROPAGATE = PROPAGATE


def new(*_args):
    _args = list(_args)
    return perllib.bless(perllib.Hash(), (_args.pop(0) if _args else None))


Class.new = types.MethodType(new, Class)
builtins.__PACKAGE__ = "Class"
builtins.__PACKAGE__ = "main"
main.obj_v = Class.new()
perllib.EVAL_ERROR = main.obj_v
perllib.die()
