#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_with_lno.pl" v1.030 run by joe on Wed Apr 19 09:52:33 2023
# part of issue_s292: die with $. in the message
import builtins, perllib, sys

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
fh = perllib.open_(f"{sys.argv[0]}", "r", checked=False)
line = perllib.readline_full(fh, "fh")
perllib.die("die with input")
