#!/usr/bin/env python3
# Generated by "pythonizer -v0 testdie/die_cannot_open.pl" v1.029 run by JO2742 on Sun Mar 26 10:44:01 2023
# part of issue_s292 - die because cannot open a file
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
main.FH = perllib.open_("non_existing", "r", checked=False)
if main.FH.closed:
    perllib.die(f"Cannot open nonexisting: {perllib.OS_ERROR}")
