#!/bin/sh
status=0
failed=0
tests=0
passed=0
flags=
for f in $*
do
   case "$f" in
   -*) flags="$flags $f"
       continue;;
   esac
   f=${f}.pl
   echo "==================== $f ===================="
   ((tests++))
   perl $f
   if [ $? -ne 0 ]; then
      echo "$f run with perl FAILED - skipping next steps"
      ((failed++))
      status=1
      continue
   fi
   ../pythonizer -v0 $flags $f
   if [ $? -ne 0 ]; then
      echo "$f run with pythonizer FAILED"
      ((failed++))
      status=1
      continue
   fi
   pyf=${f%.pl}.py
   python $pyf
   if [ $? -ne 0 ]; then
      echo "$pyf run with python FAILED"
      ((failed++))
      status=1
      continue
   fi
   ((passed++))
done;
if [ $status -eq 0 ]; then
   echo "pythonizer $tests tests PASSED!"
else
   echo "pythonizer $passed tests PASSED. $failed tests FAILED!"
   exit 1
fi
exit 0
