#!/bin/sh
export PYTHONPATH=/c/pythonizer/pythonizer
status=0
failed=0
tests=0
passed=0
flags=
prefix=
for f in $*
do
   case "$f" in
   -b*) flags="$flags $f";
       prefix="perl -d ";
       continue;;
   -B*) flags="$flags $f";
       prefix="perl -d ";
       continue;;
   -*) flags="$flags $f"
       continue;;
   esac
   pyopt=
   if [ -e ${f}.pl ]; then
       f=${f}.pl
       pyf=${f%.pl}.py
   elif [ -e ${f}.pm ]; then
       f=${f}.pm
       pyf=${f%.pm}.py
       pyopt=-m py_compile
   elif [ -e ${f}.pln ]; then
       f=${f}.pln
       pyf=${f%.pln}.py
   else
       pyf=${f}.py
   fi
   echo "==================== $f ===================="
   ((tests++))
   case "$f" in
   *.pln)   echo "Skip run with perl for $f";;
   *) perl $f
      if [ $? -ne 0 ]; then
         echo "$f run with perl FAILED - skipping next steps"
         ((failed++))
         status=1
         continue
      fi;;
   esac
   ${prefix}../pythonizer -v0 $flags $f
   if [ $? -ne 0 ]; then
      echo "$f run with pythonizer FAILED"
      ((failed++))
      status=1
      continue
   fi
   python $pyopt $pyf
   if [ $? -ne 0 ]; then
      echo "$pyf run with python FAILED"
      ((failed++))
      status=1
      continue
   fi
   ((passed++))
done;
if [ $status -eq 0 ]; then
   echo "pythonizer $tests tests PASSED!"
else
   echo "pythonizer $passed tests PASSED. $failed tests FAILED!"
   exit 1
fi
exit 0
