# test for the methods defined by use overload (generated by chatGPT)
use Carp::Assert;
use overload;
use Sub::Util 'subname';

# Test case for StrVal method
my $str = "hello world";
my $str_val = overload::StrVal($str);
assert($str_val eq "hello world", "Test StrVal method with string value");

# Test case for Overloaded method
sub overload_string { "overload string" };
use overload '""' => \&overload_string;
my $overloaded_var = bless {};
assert(overload::Overloaded($overloaded_var), "Test Overloaded method with overloaded variable");

# Test case for Method method
my $method = overload::Method($overloaded_var, '""');
assert(subname($method) eq 'main::overload_string', "Test Method method with object and method name");

assert(!overload::Method($overloaded_var, '=='));
assert(!overload::Method($overloaded_var, '<'));

print "$0 - test passed!\n";
