#!/usr/bin/env python3
# Generated by "pythonizer counter_script.pl" v1.021 run by JO2742 on Sun Jan  1 02:09:45 2023
# Implied pythonizer options: -M
# counter_script.pl
# Increments a global counter variable each time it is run
# pragma pythonizer -M
import builtins, perllib

perllib.init_package("main")
main.count_v = perllib.init_global("main", "count_v", 0)
builtins.__PACKAGE__ = "main"
main.count_v = perllib.num(main.count_v) + 1
