#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./testdo/test_script.pl" v1.021 run by JO2742 on Sun Jan  1 10:39:15 2023
## test_script.pl
## Returns the value 10
import builtins, perllib

perllib.init_package("main")
builtins.__PACKAGE__ = "main"
