#!/usr/bin/env python3
# Generated by "pythonizer -M -v0 ./otherdir/othermod.pm" v1.020 run by JO2742 on Wed Dec 21 12:01:26 2022
# part of issue_s211

import builtins, perllib

perllib.init_package("otherdir.othermod")


def otherfunc(*_args):
    return perllib.num(_args[0]) - 1


otherdir.othermod.otherfunc = otherfunc

builtins.__PACKAGE__ = "otherdir.othermod"
# SKIPPED: use Exporter 'import';
otherdir.othermod.EXPORT_OK_a = "otherfunc".split()
